services:
  - type: web
    name: jbfinancial-backend
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/JBFinancial-backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false

